name: Xeber Yenileme

on:
  schedule:
    - cron: '0 * * * *' # Hər saat başı avtomatik işləyəcək
  workflow_dispatch: # İstədiyin vaxt əllə başlatmaq üçün düymə

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu kopyala
        uses: actions/checkout@v3

      - name: Python quraşdır
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kitabxanaları yüklə
        run: pip install requests beautifulsoup4

      - name: Botu işlət
        run: python main.py

      - name: Dəyişiklikləri yadda saxla
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Xeberler yenilendi" || echo "Yeni xeber yoxdur"
          git push
